### PR TITLE
Update disqus.py

### PR DESCRIPTION
**Pull request by rmk135**
Sphinx 1.6+ keeps errors in a separate module - https://github.com/sphinx-doc/sphinx/blob/master/sphinx/errors.py

### CODE REVIEW

**Comment by mennamorato** [comment]
Is this ever going to get fixed?

**Comment by rmk135** [comment]
@mennamorato, I have no idea (

**Comment by rmk135** [comment]
As of now, you can use my fork https://github.com/rmk135/sphinxcontrib-disqus

However, I really appreciate this PR to get merged.

**Comment by mennamorato** [comment]
@rmk135  Ok thanks.. i will use your fork and see if it works but I will keep pushing on this

**Comment by shaloo** [comment]
Is this issue resolved?  I see the same error when I tried to use sphinxcontrib.disqus today. Did the fork work for you @mennamorato?

Ok, it worked for me.  Tried it just now. Thanks @rmk135

**Comment by mennamorato** [comment]
Ah ok no i did not try the fork yet but glad it worked for you.. i will try it next time

**Comment by rmk135** [comment]
Good that fork is helpful :) Still dreaming when this PR gets merged 👍

**Comment by mennamorato** [comment]
@rmk135 or  @shaloo  sorry but .. i wonder if one of you could give me a hand as a newbie here... i have downloaded @rmk135 fork for this but.. i am trying to build on my local laptop first then eventually i need to build on ReadTheDocs.  how/where do i install this new version of sphinx-contrib.disqus on my laptop [tried a few places without luck] - thanks much!

**Comment by brucedockeray-projects** [comment]
Thanks for the fork.

**Comment by rmk135** [comment]
@brucedockeray-projects , u're welcome :)

@mennamorato , I have just realized that your question from Feb 17th wasn't answered. Frankly speaking, I'm not 100% sure about what problem you were facing, but I will try to give you a headsup about how it works for me. So, that's what I did for my [Dependency Injector](https://github.com/ets-labs/python-dependency-injector)...

I have created specific [requirements file `requirements-doc.txt`](https://github.com/ets-labs/python-dependency-injector/blob/master/requirements-doc.txt) for being used both locally and by RTD. It holds required packages for building Dependency Injector documentation and also points pip to install `sphinxcontrib-disqus` from my fork on GitHub:

```
sphinx
sphinx_rtd_theme>=0.2.5b2
-e git://github.com/rmk135/sphinxcontrib-disqus.git#egg=sphinxcontrib-disqus
```

Then I went to RTD settings (`Admin -> Advanced Settings`) and:

1) Enabled checkbox for "Install your project inside a virtualenv using setup.py install".
2) Written down `requirements-doc.txt` to "Requirements file" field.

So now RTD install packages from `requirements-doc.txt` into the build environment for my project (see output of 3rd instruction here https://readthedocs.org/projects/python-dependency-injector/builds/6786616/):

```
python /home/docs/checkouts/readthedocs.org/user_builds/python-dependency-injector/envs/stable/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/python-dependency-injector/.cache/pip -rrequirements-doc.txt
```

For local development, I have `virtualenv` per each project, so I just execute next under virtualenv for Dependency Injector:

```
(venv) $ pip install -r requirements-doc.txt
```

Hope it helps, guys!

-Roman

**Comment by mennamorato** [comment]
Oh thanks perfect!

**Comment by apetros** [comment]
> -e git://github.com/rmk135/sphinxcontrib-disqus.git#egg=sphinxcontrib-disqus

Hi, is this still working? I'm trying to use it on my Netlify build. I get:

> 9:32:49 AM:   Running setup.py develop for sphinxcontrib-disqus
9:32:50 AM:     ERROR: Complete output from command /opt/buildhome/python3.7/bin/python3.7 -c 'import setuptools, tokenize;__file__='"'"'/opt/buildhome/python3.7/src/sphinxcontrib-disqus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps:
> 9:32:50 AM:     ERROR: /opt/buildhome/python3.7/lib/python3.7/site-packages/setuptools/version.py:1: UserWarning: Module sphinxcontrib was already imported from None, but /opt/buildhome/python3.7/src/sphinxcontrib-disqus is being added to sys.path

**Comment by Robpol86** [comment]
Sorry for the silence for all these years. My last job didn't let me write OSS so I stopped development of all my projects. I'll be updating this one soon. Thanks for maintaining a fork during this time.

**Comment by rmk135** [comment]
Hey @Robpol86 , glad you're back to OSS :) 👍

**Pull request merged**
